[package]
name = "xmpp"
version = "0.6.0"
authors = [
  "Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>",
  "Maxime “pep” Buquet <pep@bouah.net>",
]
description = "High-level XMPP library"
homepage = "https://xmpp.rs"
repository = "https://gitlab.com/xmpp-rs/xmpp-rs"
keywords = ["xmpp", "jabber", "chat", "messaging", "bot"]
categories = ["network-programming"]
license = "MPL-2.0"
edition = "2021"

[dependencies]
chrono = "0.4"
futures = "0.3"
tokio = { version = "1", features = ["fs", "signal"] }
log = "0.4"
reqwest = { version = "0.12", features = ["stream"], default-features = false }
tokio-util = { version = "0.7", features = ["codec"] }
# same repository dependencies
tokio-xmpp = { version = "5.0", path = "../tokio-xmpp", default-features = false }

[dev-dependencies]
env_logger = { version = "0.11", default-features = false, features = ["auto-color", "humantime"] }

[[example]]
name = "hello_bot"
required-features = ["avatars"]

[features]
default = ["avatars", "aws_lc_rs", "starttls", "rustls-native-certs"]

aws_lc_rs = ["rustls-any-backend", "tokio-xmpp/aws_lc_rs", "reqwest/rustls-tls-no-provider"]
ring = ["rustls-any-backend", "tokio-xmpp/ring", "reqwest/rustls-tls-no-provider"]
native-tls = ["tokio-xmpp/native-tls", "reqwest/native-tls"]
ktls = ["rustls-any-backend", "tokio-xmpp/ktls", "reqwest/rustls-tls"]

rustls-any-backend = ["tokio-xmpp/rustls-any-backend"]

rustls-native-certs = ["tokio-xmpp/rustls-native-certs"]
webpki-roots = ["tokio-xmpp/webpki-roots"]

starttls = ["tokio-xmpp/starttls"]

avatars = []
escape-hatch = []
syntax-highlighting = [ "tokio-xmpp/syntax-highlighting" ]
# Enable serde support in jid crate
serde = [ "tokio-xmpp/serde" ]
